# Voila- Jones Algorithm for Face, Eyes, Smile detection

In [ ]:
import numpy as np
import cv2

# Face Detection

In [3]:
img = cv2.imread('./img/ronaldo.png')
# img = cv2.imread('./img/group.jpeg')


cv2.imshow('image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
face_cascade = cv2.CascadeClassifier('./cascade_classifier/haarcascade_frontalface_default.xml')

In [5]:
faces, num_detection = face_cascade.detectMultiScale2(img)

In [6]:
print(faces)

[[659  78 296 296]]


In [7]:
print(num_detection)

[67]


In [8]:
pt1 = (659,78)

pt2 = (659+296, 78+296)

## Draw the rectangle

cv2.rectangle(img, pt1, pt2, (0, 255, 0))

cv2.imshow('fface detection', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Multiple face detection 

In [40]:
img2 = cv2.imread('./img/collegues.jpeg')

cv2.imshow('Faces', img2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [41]:
face_cascade = cv2.CascadeClassifier('./cascade_classifier/haarcascade_frontalface_default.xml')

#Apply Cascade Classifier to an Image
faces_all , num_detection2 = face_cascade.detectMultiScale2(img2, minNeighbors=8)

#Step 2 : Running a loop
for x,y,w,h in faces_all:
    cv2.rectangle(img2,(x,y),(x+w,y+h), (0,255,0))

#Step 3 : Display the Image
cv2.imshow("face detection", img2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [42]:
print(faces_all)

[[377 182 140 140]
 [537 186 188 188]
 [781 239 143 143]]


In [43]:
print(num_detection2)

[21 11 37]


# Faces And Eye Detection

In [50]:
# img2 = cv2.imread('./img/group1.jpg')
img2 = cv2.imread('./img/collegues.jpeg')


cv2.imshow('Faces', img2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [51]:
face_cascade = cv2.CascadeClassifier("./cascade_classifier/haarcascade_frontalface_default.xml")

eye_cascade = cv2.CascadeClassifier("./cascade_classifier/haarcascade_eye.xml")

In [52]:
# Step 1: Face detection
faces , num_detection_faces = face_cascade.detectMultiScale2(img2, minNeighbors = 8)
for x,y,w,h in faces:
    cv2.rectangle(img2,(x,y), (x+w, y+h), (0,255,0))
    
    # Step 2 : Cropping the face
    face_roi = img2[y:y+h, x:x+h] #image cropped
    
    # Step 3 : Eye detection
    eyes , num_detection_eyes = eye_cascade.detectMultiScale2(face_roi)
    
    for ex,ey,ew,eh in eyes:
        cx = x+ex+ew//2
        cy = y+ey+eh//2
        r = eh//2
        cv2.circle(img2,(cx,cy),r, (255,0,255),2)

# Step 4 : Show Img
cv2.imshow("face eye detection", img2)
cv2.waitKey(0)
cv2.destroyAllWindows()


# Face Eyes and Smile Detection

In [55]:
img2 = cv2.imread('./img/group1.jpg')
# img2 = cv2.imread('./img/collegues.jpeg')


cv2.imshow('Faces', img2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [56]:
face_cascade = cv2.CascadeClassifier("./cascade_classifier/haarcascade_frontalface_default.xml")

eye_cascade = cv2.CascadeClassifier("./cascade_classifier/haarcascade_eye.xml")

smile_cascade = cv2.CascadeClassifier("./cascade_classifier/haarcascade_smile.xml")

In [58]:
# Step 1: Face detection
faces , num_detection_faces = face_cascade.detectMultiScale2(img2, minNeighbors = 8)
for x,y,w,h in faces:
    face_roi = img2[y:y+h, x:x+h].copy() # Cropping the image
    cv2.rectangle(img2,(x,y), (x+w, y+h), (0,255,0))

    
    # Step 2 : Eye detection
    eyes , num_detection_eyes = eye_cascade.detectMultiScale2(face_roi)
    
    for ex,ey,ew,eh in eyes:
        cx = x+ex+ew//2
        cy = y+ey+eh//2
        r = eh//2
        cv2.circle(img2,(cx,cy),r, (255,0,255),2)
    
    #Step 3 : Smile Detection
    
    smiles, num_detection_smile = smile_cascade.detectMultiScale2(face_roi)
    for sx , sy, sw, sh in smiles:
        cv2.rectangle(img2,(x+sx, y+sy), (x+sx+sw, y+sy+sh), (255,0,0), 2)
        
    

# Step 4 : Show Img
cv2.imshow("face eye and smiles detection", img2)
cv2.waitKey(0)
cv2.destroyAllWindows()
