In [2]:
import numpy as np
import cv2

# Face Detection

In [3]:
img = cv2.imread('./img/ronaldo.png')
# img = cv2.imread('./img/group.jpeg')


cv2.imshow('image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
face_cascade = cv2.CascadeClassifier('./cascade_classifier/haarcascade_frontalface_default.xml')

In [5]:
faces, num_detection = face_cascade.detectMultiScale2(img)

In [6]:
print(faces)

[[659  78 296 296]]


In [7]:
print(num_detection)

[67]


In [8]:
pt1 = (659,78)

pt2 = (659+296, 78+296)

## Draw the rectangle

cv2.rectangle(img, pt1, pt2, (0, 255, 0))

cv2.imshow('fface detection', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Multiple face detection 

In [21]:
img2 = cv2.imread('./img/collegues.jpeg')

cv2.imshow('Faces', img2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [22]:
face_cascade = cv2.CascadeClassifier('./cascade_classifier/haarcascade_frontalface_default.xml')

#Apply Cascade Classifier to an Image
faces_all , num_detection2 = face_cascade.detectMultiScale2(img2, minNeighbors=10)

#Step 2 : Running a loop
for x,y,w,h in faces_all:
    cv2.rectangle(img,(x,y),(x+w,y+h), (0,255,0))

#Step 3 : Display the Image
cv2.imshow("face detection", img2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [23]:
print(faces_all)

[[377 182 140 140]
 [537 186 188 188]
 [781 239 143 143]]


In [24]:
print(num_detection2)

[21 11 37]
